### ISSUE TITLE
Relation to Dhall

### ISSUE THREAD

**Issue by mmhat** [Gabriel439/grace#9]
Since you are the creator of Dhall I wonder how this project of yours relates to that? As far as I can tell both projects have similar goal although Grace is a bit more restricted (i.e. primarily targeting JSON) and no remote imports but Text equality - at least that is what I have discovered so far.
The questions that came to my mind are: Is it a playground to try out new things for Dhall? Will the projects merge eventually? Or is it a study for its own sake? Basically: What was the motivation for Grace?
I guess a section in the README would be nice.

That being said, I am really excited about this project! Thank you for sharing it! :rocket:

**Comment by Gabriel439** [comment]
I'm planning to write up a post explaining the motivation behind Grace when I think the language is ready for general consumption.  The short summary is that Grace started off as an attempt to build a type-checker for Nix, which didn't pan out.  However, I didn't want to throw away what I had done so far, so I decided to change directions and turn Grace into a jsonnet replacement that other people could fork if they were interested (because I didn't want to maintain yet another language in addition to Dhall).

**Comment by mmhat** [comment]
Thank you, that made things a bit more clear to me. :+1:  As far as I am concerned this issue can be closed; I'll leave it up to you if want to track the task of writing that blog post here or elsewhere.

**Comment by Gabriel439** [comment]
You're welcome!  I'll close this, then
